import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/layout/navbar";
import Footer from "@/layout/footer";
import LenisProvider from "@/layout/lenisProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <LenisProvider>
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
